"""Initial schema

Revision ID: ec05a9ece409
Revises: 
Create Date: 2026-02-04 13:26:13.783426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec05a9ece409'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create devices first (no worker_id FK yet - circular ref with workers)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hardware_id', sa.String(length=255), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('worker_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shift_label', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_worker_id_started_at', 'sessions', ['worker_id', 'started_at'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.Enum('SEWING', 'IDLE', 'ADJUSTING', 'ERROR', 'BREAK', name='activitylabel'), nullable=False),
    sa.Column('risk_ergo', sa.Boolean(), nullable=False),
    sa.Column('risk_fatigue', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_events_session_id_ts', 'activity_events', ['session_id', 'ts'], unique=False)
    op.create_table('session_aggregates',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('active_pct', sa.Float(), nullable=True),
    sa.Column('idle_pct', sa.Float(), nullable=True),
    sa.Column('adjusting_pct', sa.Float(), nullable=True),
    sa.Column('error_pct', sa.Float(), nullable=True),
    sa.Column('alert_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # Add worker_id FK to devices (workers now exists)
    op.create_foreign_key(
        'fk_devices_worker_id', 'devices', 'workers',
        ['worker_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_devices_worker_id', 'devices', type_='foreignkey')
    op.drop_table('session_aggregates')
    op.drop_index('ix_activity_events_session_id_ts', table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index('ix_sessions_worker_id_started_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('workers')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
